### ISSUE TITLE
Close reports

### ISSUE THREAD

**Issue by wasabirosso** [frederiksen/Task-Card-Creator#4]
Hi,

is there a way to Close all reports? I am trying to figure out which template is the best for our Team, but I still cannot find a way to Close all reports.
thanks in advanced!

Kind regards

![cardsreports](https://user-images.githubusercontent.com/30236556/28271653-732328de-6b09-11e7-9e6b-3a4e4f7050b8.jpg)

**Comment by frederiksen** [comment]
@wasabirosso you are right - currently it is not possible to close a report. It would be a nice feature - if anyone would like to implement this - please send a PR

**Comment by Timur-Hasan** [comment]
@frederiksen I've created a pull request to do this.

**Comment by Timur-Hasan** [comment]
![image](https://user-images.githubusercontent.com/12498390/48361496-8759e380-e699-11e8-9272-7d0bc6b85b6b.png)

**Comment by frederiksen** [comment]
Fixed in https://github.com/frederiksen/Task-Card-Creator/pull/9
